<a href="https://colab.research.google.com/github/sprince0031/ICT-Python-ML/blob/main/Week%203/Notebooks/Week3.ipynb" target="_blank"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python & ML Foundations: Session 3
## NumPy & Pandas

Welcome to the session 3 tutorial and companion notebook! This week, we'll learn to do basic mathematical operations of n-dimensional arrays using NumPy and pre-process a real-world housing dataset that's available in colab's sample folder.

## Utility code
The below code cell contains any common imports or sample data that can be useful for your exercises. Make sure to run this cell first before starting your exercises!

In [1]:
import pandas as pd
import numpy as np

---
# Video Challenges

## 1. NumPy

This assignment tests your ability to use NumPy to prepare a dataset for a machine learning task. Use `np.random.seed(42)` to ensure your results are reproducible.

### Create a Dataset
Create a 10x4 NumPy array representing 10 houses with the following columns:
* **Square Footage:** Random integers from `1000` to `3000`
* **Bedrooms:** Random integers from `2` to `6`
* **House Age:** Random integers from `1` to `50`
* **House Price:** Random floats from `150.0` to `750.0`

Print the resulting array

### Filter the Data
Using boolean indexing, create a new array containing only the houses with more than 3 bedrooms and an age of less than 20 years.

Print the filtered array and its `.shape`.


In [30]:
# Your code here

# Create numpy 10x1 arrays for each of the columns
np.random.seed(42)
square_footage=np.random.randint(1000,3001,10)
bedrooms=np.random.randint(2,7,10)
house_age=np.random.randint(1,51,10)
house_price=np.random.uniform(150.0,750.0,10)
print(square_footage)
print(bedrooms)
print(house_age)
print(house_price)


# Colate the arrays into a single 10x4 array
house_data = np.column_stack((square_footage,bedrooms,house_age, house_price) )

print(f'Full house data:\n{house_data}')


[2126 2459 1860 2294 2130 2095 2724 2044 2638 1121]
[4 4 4 6 5 4 6 3 5 3]
[21 33 12 22 44 25 49 27 42 28]
[734.2533113  289.66280426 204.36386072 521.0316056  379.47719476
 739.93853148 430.05773595 665.96424404 558.18452315 420.29955118]
Full house data:
[[2126.            4.           21.          734.2533113 ]
 [2459.            4.           33.          289.66280426]
 [1860.            4.           12.          204.36386072]
 [2294.            6.           22.          521.0316056 ]
 [2130.            5.           44.          379.47719476]
 [2095.            4.           25.          739.93853148]
 [2724.            6.           49.          430.05773595]
 [2044.            3.           27.          665.96424404]
 [2638.            5.           42.          558.18452315]
 [1121.            3.           28.          420.29955118]]


In [ ]:
# Filter data
house_data

# Print filtered numpy array and its shape

## 2. Pandas

**Run the Data Corruption Code:**

It will load the test dataset and introduce several common data quality issues.

In [ ]:
# --- RUN THIS CODE FIRST ---
# This code will create a corrupted DataFrame for you to fix.

# Load the test dataset
test_path = '/content/sample_data/california_housing_test.csv'
df_challenge = pd.read_csv(test_path)

# Introduce NaN values
df_challenge.loc[[5, 20, 50], 'total_rooms'] = np.nan
df_challenge.loc[[10, 30, 60], 'population'] = np.nan

# Introduce extreme outliers
df_challenge.loc[[100, 200], 'housing_median_age'] = 999

# Introduce incorrect data type
df_challenge['households'] = df_challenge['households'].astype(str)

print("--- Corrupted Dataset is Ready ---")
df_challenge.info()

**Clean the Data**

Now, write the code to fix the `df_challenge` DataFrame.

 * **Inspect the Damage:** After running the code above, use `.info()` and `.describe()` to identify all the problems that were introduced.

 * **Fix Data Types:**  The households column was incorrectly converted to an object (string). Convert it back to a numeric type. Hint: Use `pd.to_numeric()`

 * **Handle Missing Values:** Fill the `Nan` values in `total_rooms` and population with their respective means.

 * **Handle Outliers:** The `housing_median_age` column now has unrealistic values. Filter the DataFrame to remove any rows where `housing_median_age` is greater than `90`.

 Print the `.info()` and `.describe()` outputs of your final, cleaned DataFrame to prove that all the issues have been resolved.

In [ ]:
# Your code here


---
# Practice Challenges

## Video Game Sales Analysis

This exercise will guide you through a basic data analysis project to practice your data loading, cleaning, and exploration skills using pandas for data manipulation and numpy for numerical calculations.

 We will be using the Video Game Sales dataset from Kaggle.
 * You can download it here: https://www.kaggle.com/datasets/gregorut/videogamesales


### Step 1: Setup and Data Loading

 Make sure you have uploaded the `vgsales.csv` file to your Colab environment.

* Load the `vgsales.csv` file into a pandas DataFrame named df.
* Display the first 5 rows of the DataFrame using `df.head()` to ensure it's loaded correctly.


In [ ]:
# Your code here

### Step 2: Data Cleaning and Initial Exploration

* Use `df.info()` and `df.isnull().sum()` to check for missing values in each column.
* Remove the rows with missing values using `df.dropna(inplace = True)`.
* The `Year` column is a float but should be an integer. Covert it to int.
* Print the info again to confirm your changes.

In [ ]:
# Your code here

### Step 3: Answering Analytical Questions

**Question 1:  Which publisher has released the most games?**

***Hint:*** Use the .value_counts() method on the Publisher column.

**Question 2: Which genre sold the most copies in North America?**

***Hint:***  Use .groupby() on the Genre column, select the NA_Sales column, and calculate the .sum().

**Question 3: What is the standard deviation of global sales for the "Action" genre?**

***Hint:***  First, filter the DataFrame to get only "Action" games. Then, select the Global_Sales column and use the .std() method (which uses numpy underneath).

In [ ]:
# Your code here

## Bonus Challenge

Calculate the total global sales for each platform and determine which platform has the highest market share (percentage of total global sales).

In [ ]:
# Your code here